name = "nomi-ceu - 1.6.1a"
author = "__tracer"
version = "1.6.1a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a28052e022eab337819dd9c1102e8d8fe0ce2ab7fd9db89924e0e6036744bcf6"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
