name = "nomi-ceu - 1.6.1a"
author = "__tracer"
version = "1.6.1a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b1807a9fb29e529faf1a3da81ddc65dd2e8f70bc80420516166f9884d4c558d"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
