name = "nomi-ceu - 1.6.1a"
author = "__tracer"
version = "1.6.1a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77673bd08ee867baa06b0b8ae688d1b52b4864b87ceda26ca8d93e0b295b0467"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
