name = "nomi-ceu - 1.6.1a"
author = "__tracer"
version = "1.6.1a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed8109753ccf2e08cdbf1bc62efead8a182b1e5118952a737ba66bf2f8a6af4e"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
