name = "nomi-ceu - 1.6.1a"
author = "__tracer"
version = "1.6.1a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e10be83bf2f84dad2546724efa4a9cc90b7c4924c8ecf3df42716d2cae2017f"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
