name = "nomi-ceu - 1.6.1a"
author = "__tracer"
version = "1.6.1a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9774a83efa0f4e3be38bfe7a12e2de37105f102cea9fd51567d776c4c10ef41"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
